src/configs/test/apps.yaml
Reverts CityOfBoston/access-boston-config#40
=> Revert "Test Environment - Birthright Visibility"

src/configs/dev/apps.yaml
Reverts CityOfBoston/access-boston-config#39
=> Revert "Dev Environment - Update Birthright visibility"

src/configs/test/apps.yaml
New App Tile - United Way, Employee Giving
=> TEST Env: New App Tile - United Way

src/configs/prod/apps.yaml
New App Tile - United Way, Employee Giving
=> PROD Env: New App Tile - United Way

src/configs/prod/apps.yaml
Groups need to be entered as all uppercase
=> Fix SCERIS title groups

src/configs/prod/apps.yaml
- New Tile, Beacon
- Rebrand `ServiceNow` to `ServiceNow - LightKeeper`
=> PROD Deploy: New Tile Beacon

src/configs/prod/apps.yaml
Ticket: https://github.com/CityOfBoston/digital/issues/847
=> (PROD) Deploy New Tile - CyberArk

src/configs/prod/apps.yaml
Reverts CityOfBoston/access-boston-config#112
=> Revert "[PROD] Update Career Ctr URL"

src/configs/prod/apps.yaml
=> [PROD] BAIS Banner Notice Change

src/configs/test/apps.yaml
Reverts CityOfBoston/access-boston-config#142
=> Revert "[TEST] Employee Training Name Change"

src/configs/prod/apps.yaml
[PROD] Change Employee Training Name
=> [PROD] Change Employee Training Name

src/configs/prod/apps.yaml
ABP Banner for AGP Cloud Maintenance
=> [PROD] DIG-1969: ABP Banner for AGP Maintenance

src/configs/test/apps.yaml
ABP Banner for AGP Cloud Maintenance
=> [TEST] DIG-1969: ABP Banner for AGP Maintenance

src/configs/dev/apps.yaml
ABP Banner for AGP Cloud Maintenance
=> [DEV] DIG-1969: ABP Banner for AGP Maintenance

src/configs/test/apps.yaml
Reverts CityOfBoston/access-boston-config#198
=> Revert "[TEST] DIG-4249: Genasys Admins"

src/configs/prod/apps.yaml
Update Banner on ABP PROD - Add The Supplier Portal to list
=> [PROD] DIG-4436

src/configs/test/apps.yaml
Update ABP with Dev and Test Icons URLs to validate login against PROD creds
=> [TEST] DIG-4299: Update ABP with DEV/TEST with Drupal Grp

src/configs/prod/apps.yaml
* DIG-4114: Replace Travis deploy with Github Actions #v2 (#218)
* [PROD] S3 Deploy Test - Remove Banner
=> [MAIN] Deploy-Prod/Test s3 Deploy v1 (#219)

src/configs/prod/apps.yaml
- Add banner to ABP - See langage above
- Remove Hub icon from APB
- Make Beacon birthright
=> [PROD] DIG-4410: Remove HUB, make Beacon birthright

src/configs/test/apps.yaml
=> [TEST] DIG-5085: Update Riskmaster and Xybrion URL

src/configs/prod/apps.yaml
- [DIG-5458: Add BidBot Icon/URL -ABP PROD](https://bostondoit.atlassian.net/browse/DIG-5458)
- [DIG-5479: APB Banner for year-end tax confirmation](https://bostondoit.atlassian.net/browse/DIG-5479)
=> [PROD] DIG-5458/5479
